package genad.gui.misc;

import java.util.*;
import javax.swing.table.*;

import genad.*;
import genad.config.*;
import genad.model.*;

/**
 *
 * @author  kronenthaler
 */
public class ReplaceFilesDlg extends javax.swing.JDialog {
	private ArrayList<DelayedFile> files;
    /** Creates new form ReplaceFilesDlg */
    public ReplaceFilesDlg(java.awt.Frame parent, boolean modal, ArrayList<DelayedFile> _files) {
        super(parent, modal);
        initComponents();
		files=_files;
		
		//crear el model de la tabla.
		ArrayList<Object[]> buf=new ArrayList<Object[]>();
		for(DelayedFile df : files){
			buf.add(new Object[]{df.getPath().substring(Model.getInstance().getDestinationPath().length()),!df.getFile().exists()});
		}
		
		DefaultTableModel model =new javax.swing.table.DefaultTableModel(
				buf.toArray(new Object[0][]),
				new String [] { "File", "Override" }
			) {
			
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

			@Override
			public boolean isCellEditable(int row, int column){
				return column != 0;
			}
			
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
		jTable1.setModel(model);
		
		Utils.centerComponent(this);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Replace files");

        jLabel1.setText("The following files already exists, select which one override.");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "File", "Override"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(IconsManager.OK);
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 376, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	//recorrer la tabla y llamar el metodo ejecutar de aquellos que tengan el valor de la columna 1 en true.
	
	Vector<Vector> data=(Vector<Vector>)((DefaultTableModel)jTable1.getModel()).getDataVector();
	
	for(int i=0;i<data.size();i++){
		Vector v=data.get(i);
		if(((Boolean)v.get(1))){
			files.get(i).create();
		}
	}
	
	dispose();
	setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton1;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
