<?
include_once('obj/User.php');
include_once('obj/Profile.php');
include_once('obj/Permission.php');
include_once('obj/Section.php');
include_once('obj/UserProfile.php');
include_once('obj/ProfilePermission.php');
$_SESSION['modules']->enableModule('/users/admin/js/validators.js');
?>